=== meinders/lithium/lithium-core/src/main/resources/dtds/config.dtd
<!-- PUBLIC "-//Frixus//DTD opwViewer Configuration 1.0//EN"
"config.dtd" -->

<!--
version:    0.8 (2005.08.04)
author:     Gerrit Meinders
-->

<!ELEMENT config (display*, catalogs, default-bundel, scrollbar, divider,
        recent-files?, auto-scroll?, background?)>

<!ELEMENT display (device?, mode?)>
<!ATTLIST display           id              CDATA   #REQUIRED>

<!ELEMENT device (EMPTY)>
<!ATTLIST device            id              CDATA   #REQUIRED>

<!ELEMENT mode (EMPTY)>
<!ATTLIST mode              width           CDATA   #REQUIRED
                            height          CDATA   #REQUIRED
                            bitDepth        CDATA   #REQUIRED
                            refreshRate     CDATA   #REQUIRED>

<!ELEMENT catalogs (catalog*)>

<!ELEMENT catalog (EMPTY)>
<!ATTLIST catalog           url             CDATA   #REQUIRED>

<!ELEMENT default-bundel (EMPTY)>
<!ATTLIST default-bundel    id              CDATA   #REQUIRED>

<!ELEMENT scrollbar (EMPTY)>
<!ATTLIST scrollbar         visible         (true|false)
                                                    #REQUIRED>

<!ELEMENT divider (EMPTY)>
<!ATTLIST divider           visible         (true|false)
                                                    #REQUIRED>
<!ELEMENT recent-files (recent-file*)>

<!ELEMENT recent-file (EMPTY)>
<!ATTLIST recent-file       name            CDATA   #REQUIRED>

<!ELEMENT auto-scroll (EMPTY)>
<!ATTLIST auto-scroll       speed           CDATA   #IMPLIED
                            delay           CDATA   #IMPLIED
                            rate            CDATA   #IMPLIED>

<!ELEMENT scroller   (EMPTY)>
<!ATTLIST scroller          type            (plain|smooth)
                                                    "smooth"
                            units           (characters|lines)
                                                    "lines">

<!ELEMENT background (EMPTY)>
<!ATTLIST background        color           CDATA   #IMPLIED
                            image           CDATA   #IMPLIED
                            visibleInPreview
                                            (true|false)
                                                    "false">

=== meinders/lithium/lithium-core/src/test/resources/lithium/io/oldConfig.xml
<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE config PUBLIC "-//Frixus//DTD opwViewer Configuration 1.0//EN" "config.dtd">
<config>
  <display id="editor">
    <device id="\Display0"/>
  </display>
  <display id="presentation"/>
  <catalogs>
    <catalog url="newcatalog.xml"/>
    <catalog url="opwekking.xml"/>
    <catalog url="spoorzicht.xml"/>
  </catalogs>
  <default-bundle id="Opwekking"/>
  <scrollbar visible="true"/>
  <divider visible="true"/>
  <recent-files>
    <recent-file name="D:\Code\Java\Projects\opwViewer\dist\newcatalog.xml"/>
  </recent-files>
  <auto-scroll speed="0.4"/>
  <background color="#0040c0" image="images/backgrounds/Blue%20Waves.png" visibleInPreview="false"/>
  <scroller type="smooth" units="lines"/>
  <utilities>
    <utility location="C:\Program Files\Microsoft Office\PowerPoint Viewer\PPTVIEW.EXE" name="ppt"/>
  </utilities>
</config>
